Update deploy

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,5 +1,18 @@
 #!/usr/bin/env bash
 
+read -p "Enter username : " username
+read -s -p "Enter password : " password
+egrep "^$username" /etc/passwd >/dev/null
+if [ $? -eq 0 ]; then
+  echo "$username exists!"
+  exit 1
+else
+  pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
+  useradd -m -p $pass $username
+  [ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
+fi
+  
+  
 # First we need to update to latest packages so there should be security and bug fixes
 
 sudo apt update
@@ -139,6 +152,10 @@ service mysql restart
 systemctl enable supervisor.service
 service supervisor start
 
+# Disable root login
+sed -i '/^PermitRootLogin[ \t]\+\w\+$/{ s//PermitRootLogin no/g; }' /etc/ssh/sshd_config
+cp -r /root/.ssh /home/$username
+chown -R $username:$username /home/$username/.ssh
 
 # One last upgrade check
 
@@ -149,7 +166,9 @@ apt-get -y upgrade
 apt-get -y autoremove
 apt-get -y clean
 
-#We may have purchased lowest price machine having low ram. So we can create swap that will serve as ram purpose
+
+
+# We may have purchased lowest price machine having low ram. So we can create swap that will serve as ram purpose
 
 /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
 /sbin/mkswap /var/swap.1
